services:
  frontend: 
    image: nextjs_frontend
    ports: 
      - "3000:3000"
    build: 
      context: ./frontend
  backend:
    image: rust_backend
    depends_on: 
      - db
    ports: 
     - "7878:7878"
    env_file:
      - ./backend/.env.docker
    build:
      context: ./backend
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "password1"
      MARIADB_DATABASE: thehub
    ports:
      - "3367:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - mariadb_data1:/var/lib/mysql

volumes:
  mariadb_data1:
